# The version number of the release
release: "2024.07.01"
release2: "2024.07.01"

# The folder where the raw data for all batches are saved
raw_folder: "/mnt/archive/Momics/MomicsPub/snpArray/Datasets"

# Global paths
documentationDataset: "https://github.com/fhi-beta/mobaDocsBackoffice/wiki/MoBaGenPub"
documentationQC: "https://github.com/fhi-beta/mobaDocsBackoffice/wiki/pipeline"
githubSource: "https://github.com/fhi-beta/mobaGenetics-qc"
output_base: "/mnt/work/qc_genotypes/pipeOut_dev"
archive_output_base: "/mnt/archive/snpQc/pipeOut_dev"
release_base: "/mnt/archive/moba_genotypes_releases"

# Phenotypes
expected_relationships: "/mnt/archive/snpQc/phenotypes/expected_relationship_24.04.12.gz"
birth_year: "/mnt/archive/snpQc/phenotypes/birth_year_24.04.12.gz"
id_mapping: "/mnt/archive/snpQc/phenotypes/ids_24.08.07.gz"

# from http://www.haplotype-reference-consortium.org/ http://www.haplotype-reference-consortium.org/site
# contains HRC.r1-1.GRCh37.wgs.mac5.sites.tab. If not found - google it.
# Used by the Will Rayner perl-script in mod5.
hrc_sites: "/mnt/archive/snpQc/HRC/HRC.r1-1.GRCh37.wgs.mac5.sites.tab"
hrc_ega: "/mnt/archive/HRC_1.1_EGA/24.05.30"
hrc_bref: "/mnt/archive/HRC_bref3"

# Genetic maps found at https://bochet.gcc.biostat.washington.edu/beagle/genetic_maps/
mapfiles: "/mnt/archive/genetic_maps"

# From https://github.com/long-covid-hg/pca_projection/blob/main/docs/prerequisites.md#download-the-pre-computed-pca-loadings-and-reference-allele-frequencies
# Contains precomputed PCA loadings and reference allele frequencies from Human Genome Diversity Project (HGDP) and the 1000 Genomes Project
# Not used at this stage
ref_pc_loadings: "/mnt/archive/snpQc/pc_loadings/hgdp_tgp_pca_covid19hgi_snps_loadings.GRCh37.plink.tsv"
ref_pc_freq: "/mnt/archive/snpQc/pc_loadings/hgdp_tgp_pca_covid19hgi_snps_loadings.GRCh37.plink.afreq"
hgdp_weights: "/mnt/archive/snpQc/pc_loadings/hgdp_tgp_pca_covid19hgi_snps_scores.txt.gz" # HGDP weights, see github.com/covid19-hg/pca_projection for details

# 1000 genomes data used for PCA
# See https://cran.r-project.org/web/packages/plinkQC/vignettes/Genomes1000.pdf
# Reference is p37
1000_genomes_stem: "/mnt/archive/snpQc/1000Genomes/all_phase3"
1000_genomes_pop:  "/mnt/archive/snpQc/1000Genomes/all_phase3.psam"

# See https://genome.sph.umich.edu/wiki/Regions_of_high_linkage_disequilibrium_(LD)
high_ld_regions_hg19: "/mnt/work/gutorm/git/mobaGenetics-qc/qc-pipeline/resources/high-ld-regions-hg19"

# Thresholds and names of the columns in snp table file
cluster_sep_thr: 0.40
10%_GC_score_thr: 0.30
10%_GC_score_col_name: "10% GC"
aa_theta_dev_thr: 0.04

#
# Minor allele frequency threshold used during pedigree inference
pedigree_maf_thr: 0.10
# Missing genotype threshold (samples) used during pedigree inference
pedigree_mind_thr: 0.05
# Hardy-Weinberg equilibrium threshold (samples) used during pedigree inference
pedigree_hwe_thr: 0.0001
# Missing genotype threshold (markers) plink --geno
geno_thr: 0.02
# prune_markers --make founders (command and params).
prune_cmd: --indep-pairwise 200 100 0.1
# Minor allele count to use for pedigree and PCA in the merged set
merged_set_best_snps_mac_thr: 500
# Missing genotype threshold (markers) for pedigree and PCA in the merged set
merged_set_best_snps_geno_thr: 0.05
# Info score threshold for good markers
merged_set_best_snps_info_thr: 0.9

# Maf threshold for the release
release_maf_thr: 0.001
# HW threshold for the release
release_hw_thr: 0.0000001
# sd het threshold for the release
release_sd_het_thr: 4

# Kinship thresholds to create the set of good markers
kinship_threshold: 0.1 # Used for the direct relatedness (not Djenghis Khan effect)
accum_kinship_threshold: 0.015   # Threshold for normalized accumPIHAT to determine outliers

# 3 cycles of mind/geno removal
geno_rate.geno1: 0.10
geno_rate.mind1: 0.05
geno_rate.geno2: 0.05
geno_rate.mind2: 0.03
geno_rate.geno3: 0.02
geno_rate.mind3: 0.02

# Rule that works with hwe/het - 2 cycles followed by geno
hwe1: 0.0000001
maf1: 0.01
sd_het1: 4
hwe2: 0.000001
maf2: 0.01
sd_het2: 4
geno_rate: 0.020

sex_check_female: 0.2
sex_check_male: 0.8  # plink 1.9 default
sex_check_indep_pairwise: 20000 2000 0.5

# used for all samples in several rules
xmarkers_clean: 0.000001

n_samples: "all"

# memory and thread allocation
mem: "100g"
beagle_threads: 32
mod6conform_threads: 2
mod6conform_mem: "7g"
mod6impute_threads: 32
mod7_convert_chrs_to_pgen_threads: 8
mod7_convert_chrs_to_pgen_mem: "12500"

# mod7
combined_dr2_threshold: 0.9
batch_dr2_threshold: 0.7
counts_threshold: 500

chrs_debug: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']
batches_debug: ['snp001', 'snp002', 'snp003', 'snp007', 'snp008', 'snp009', 'snp010', 'snp011', 'snp012', 'snp014', 'snp015a', 'snp015b', 'snp016a', 'snp016b', 'snp017a', 'snp017b', 'snp017c', 'snp017d', 'snp017e', 'snp017f', 'snp018a', 'snp018b', 'snp018c', 'snp018de']

# parameters to finalize core
# core_mind: 0.02

# Same limits for common/rare
# core_maf: 0.01
# core_sd_het: 4





