# The folder where the raw data for all batches are saved
raw_folder: "/mnt/archive/Momics/MomicsPub/snpArray/Datasets"

# Global paths
documentationDataset: "https://github.com/fhi-beta/mobaDocsBackoffice/wiki/MoBaGenPub"
documentationQC: "https://github.com/fhi-beta/mobaDocsBackoffice/wiki/pipeline"
githubSource: "https://github.com/fhi-beta/mobaGenetics-qc"
output_base: "/mnt/archive/snpQc/pipeOut_dev_2024.01.05"

# Phenotypes
expected_relationships: "/mnt/archive/snpQc/phenotypes/expected_relationship_24.04.12.gz"
birth_year: "/mnt/archive/snpQc/phenotypes/birth_year_24.04.12.gz"

# from http://www.haplotype-reference-consortium.org/ http://www.haplotype-reference-consortium.org/site
# contains HRC.r1-1.GRCh37.wgs.mac5.sites.tab. If not found - google it.
# Used by the Will Rayner perl-script in mod5.
# 2.8Gig
hrc_sites: "/mnt/archive/snpQc/HRC/HRC.r1-1.GRCh37.wgs.mac5.sites.tab"

# From https://github.com/long-covid-hg/pca_projection/blob/main/docs/prerequisites.md#download-the-pre-computed-pca-loadings-and-reference-allele-frequencies
# Contains precomputed PCA loadings and reference allele frequencies from Human Genome Diversity Project (HGDP) and the 1000 Genomes Project
# Used for population clustering
ref_pc_loadings: "/mnt/archive/snpQc/pc_loadings/hgdp_tgp_pca_covid19hgi_snps_loadings.GRCh37.plink.tsv"
ref_pc_freq: "/mnt/archive/snpQc/pc_loadings/hgdp_tgp_pca_covid19hgi_snps_loadings.GRCh37.plink.afreq"

# 1000 genomes data used for PCA
# See https://cran.r-project.org/web/packages/plinkQC/vignettes/Genomes1000.pdf
# Reference is p37
1000_genomes_stem: "/mnt/archive/snpQc/1000Genomes/all_phase3"
1000_genomes_pop:  "/mnt/archive/snpQc/1000Genomes/all_phase3.psam"
# prune parameters identic to those used for moba. Not necessary? (2020.02.19) Delete if not used 
#1kgp_maf_thr: 0.1 
#1kgp_prune_cmd: --indep-pairwise 200 100 0.1

# HGDP data used for PCA, see github.com/covid19-hg/pca_projection for details
hgdp_weights: "/mnt/archive/snpQc/pc_loadings/hgdp_tgp_pca_covid19hgi_snps_scores.txt.gz"


# hapmap ... Old reference set b36 - We switch to G1000
# note that there is a full set bedset here ...
#hapmap,stem: /mnt/archive/helgeland/refdata/hapmap/hapmap_b36/hapmapb36"
#hapmap_pop: "/mnt/archive/helgeland/refdata/hapmap/relationships_w_pops_121708.txt"

# See https://genome.sph.umich.edu/wiki/Regions_of_high_linkage_disequilibrium_(LD)
high_ld_regions_hg19: "/mnt/work/gutorm/git/mobaGenetics-qc/qc-pipeline/resources/high-ld-regions-hg19"

# Thresholds and names of the columns in snp table file
cluster_sep_thr: 0.40
10%_GC_score_thr: 0.30
10%_GC_score_col_name: "10% GC"
aa_theta_dev_thr: 0.04

#
# Minor allele frequency threshold used during pedigree inference
pedigree_maf_thr: 0.10
# Missing genotype threshold (samples) used during pedigree inference
pedigree_mind_thr: 0.05
# Hardy-Weinberg equilibrium threshold (samples) used during pedigree inference
pedigree_hwe_thr: 0.0001
# Missing genotype threshold (markers) plink --geno
geno_thr: 0.02
# prune_markers --make founders (command and params).
prune_cmd: --indep-pairwise 200 100 0.1

# these two files have been produced by Jonas by hand and have better pedigree info than we had
# We want to automate this - but for now (2019) we are just keeping it as it is
# These files comes from a PC environment and have ^M in them
# Note that the whole section will probably be removed and put into another (pre?) pipeline
# infer_recfam: "/mnt/archive2/MomicsSource/snpArray/snp014/ROTTERDAM2/delivery-fhi/documentation/inferred-pedigree/permanent_reconstruct-fam.txt"
# infer_badids: "/mnt/archive2/MomicsSource/snpArray/snp014/ROTTERDAM2/delivery-fhi/documentation/inferred-pedigree/permanent_bad-sample-IIDs.txt"


# needed? CHECK!
# pca_thr: "6 0.015 NA 0.0355 NA"

# Kinship thresholds to create the set of good markers
kinship_threshold: 0.1 # Used for the direct relatedness (not Djenghis Khan effect)
accum_kinship_threshold: 0.015   # Threshold for normalized accumPIHAT to determine outliers

# 3 cycles of mind/geno removal
geno_rate.geno1: 0.10
geno_rate.mind1: 0.05
geno_rate.geno2: 0.05
geno_rate.mind2: 0.03
geno_rate.geno3: 0.02
geno_rate.mind3: 0.02

# Rule that works with hwe/autosomatic-het/geno - 2 cycles
hwe1: 0.0000001
maf1: 0.01
sd_het1: 4
hwe2: 0.000001
maf2: 0.01
sd_het2: 4
geno_rare: 0.020

sex_check_female: 0.2
sex_check_male: 0.8  # plink 1.9 default
sex_check_indep_pairwise: 20000 2000 0.5


# used for all samples in several different rules
xmarkers_clean: 0.000001

# parameters to finalize core
core_mind: 0.02

# Same limits for common/rare
core_maf: 0.01
core_sd_het: 4




