#
# the maximum number of threads the pipeline can use. Change this when/if more resources available
nthread: 1

# max sample size to use in one batch. This is hardware dependent. If
# 120GB memmory, 1000 EPIC samples or 1700 450k samples can be run at
# once. If 60GB memmory, 500 EPIC or 850 450k samples can be run at
# once.
max_sample_size_epic: 500
max_sample_size_450k: 850

# renv controls if renv should be used for package control or not. creates some modifications to the scripts
# if on TSD, renv should be TRUE. If outside of TSD, renv should be FALSE
renv: FALSE

# data path:
# global_path: "/tsd/p229methylation/data/durable/Datasets" 
global_path: "/mnt/archive/Momics/MomicsPub/Methylation/Datasets"
output_path: "/mnt/archive/gutorm/methylationRuns"

# rule 2
filter_cross_hybridizing: TRUE
filter_polymorphic_CpGs: TRUE

# rule 2 parameters
sample_groups: "Slide"

# rule 4 parameters
# Set the p-value cut-off for calling CpG probes as detected
# We recommend leaving this as default unless you have a good justification
detection_pvalue: 0.01
poor_quality_frac: 0.05

# rule 4 parameters
# Set the minimum bisulphite conversion rate for a sample to pass QC
# We recommend lieaving this as default unless you have a good justification
bisulphite_conversion_rate: 90

# Which preprocessing methods to compare in rule 5
# We recommend you leave this as is to get a good comparison of
#   how each normalization method performs on your data.
#   Other options: Funnorm, Illumina, SWAN etc
preprocess_methods: [Noob]

# Based on the results from the previous rule, which preprocessing method is optimal?
selected_preprocess_method: Noob

