# Used to set variables common for all datasets
# Location of inputfiles (assumes a certain dir structure below)
# root_data_path: "/tsd/p229methylation/data/durable/Datasets"
root_data_path: "/tsd/p229methylation/data/durable/Datasets"
# Where to put the result
output_path: "/tsd/p581/data/durable/Projects/MoBa_genomics/moba_qc_pipeline/Runs"

# max sample size to use in one batch. This is hardware dependent. If
# 120GB memmory, 800 EPIC samples or 1400 450k samples can be run at
# once. If 60GB memmory, 400 EPIC or 700 450k samples can be run at
# once.
max_sample_size_epic: 500
max_sample_size_450k: 1000

# renv controls if renv should be used for package control or not. creates some modifications to the scripts
# if on TSD, renv should be TRUE. If outside of TSD, renv should be FALSE
renv: TRUE

# rule 2
filter_cross_hybridizing: TRUE
filter_polymorphic_CpGs: TRUE

# rule 2 parameters
sample_groups: "Slide"

# rule 4 parameters
# Set the p-value cut-off for calling CpG probes as detected
# We recommend leaving this as default unless you have a good justification
detection_pvalue: 0.01
poor_quality_frac: 0.05

# rule 4 parameters
# Set the minimum bisulphite conversion rate for a sample to pass QC
# We recommend lieaving this as default unless you have a good justification
bisulphite_conversion_rate: 90

# size of CpG subset used for plotting
subset_plotting: 50000

# size of CpG subset for fitting within the BMIQ function 
subset_BMIQ: 25000
# Which preprocessing methods to compare in rule 5
# We recommend you leave this as is to get a good comparison of
#   how each normalization method performs on your data.
#   Other options: Funnorm, Illumina, SWAN etc
preprocess_methods: [Noob]

# Based on the results from the previous rule, which preprocessing method is optimal?
selected_preprocess_method: Noob

