# Used by various reporting to describe the set

dataSet: "Norment (biobank retrieval 954, V1 chip)"
chip: "DeCodeGenetics_V1"
# Name the raw plink files
# a_b_c-chip.version
# this will both be the name of the plinkset as well as default family name
rawPlink: "954-deCODE.V1"
documentationDataset: "https://github.com/folkehelseinstituttet/mobaDocsBackoffice/wiki/MoBaGenPub"
documentationQC: "https://github.com/folkehelseinstituttet/mobaDocsBackoffice/wiki/pipeline"
githubSource: "https://github.com/folkehelseinstituttet/mobaGenetics-qc"

#plinklocal: "/mnt/work/gutorm/git/mobaGenetics-qc/qc-pipeline/bin/plink-1.90b5.4/plink"
plinklocal: "../../../qc-pipeline/bin/plink-1.90b5.4/plink"

# Lab QC report: /mnt/archive/ROTTERDAM2/delivery-fhi/data/raw-data/lab-report/GSA2017_246_QC_report.pdf

# This is the set as it was received it from the lab (for norment: deCODE)
# original_data_dir: "/mnt/work2/NORMENT1/JAN20/MorBarn.DeCodeGenetics_V1_20012591_A1.plink.dir/"
raw_bed_stem_in: "/mnt/work2/NORMENT1/JAN20/MorBarn.DeCodeGenetics_V1_20012591_A1.plink.dir/MorBarn.DeCodeGenetics_V1_20012591_A1"
raw_bed_dir_out: "/home/gthh/work/gutorm/MobaGenetics/Datasets/Norment_2a/raw-data"

# The following file is typically made by hand/grep It has no headers
# and is typically made from the samplesheet. Sometime (in case of
# duplicates) it needs to be tweaked. It should have the same number
# of rows as the plinkfiles.
remap_id: "/mnt/work2/NORMENT1/JAN20/sampleCheck/retrievalID_to_sentrixId"
# The mapping above will produce something suitable for plink
recode_ids: "/mnt/work2/NORMENT1/JAN20/sampleCheck/retrievalID_to_sentrixId_4_plink"


