# Usage: snakemake --config-file configs/your-config

sys.path.append('../../../qc-pipeline/lib/')  # in order to find our local packages
import mobaQcTools as mqc  # local moba package

# There are multiple configfiles, choose the right one as a snakemake param
# configfile: "Friendly reminder: Use --configfile configs/whatever" 

# Report (top level) (for now we dont need/use it. --report still works
# report: "report/qc.rst"

rule all:
    input: recode_ids=config["recode_ids"],

# rule all
rule make_plink:
    input:
        bedset=multiext(config["raw_bed_stem_in"],".bed",".bim",".fam"),
        biobank2sentrix_map=config["remap_id"]
    output:
        recode_ids=config["recode_ids"],
        bedset=multiext(config["raw_bed_dir_out"]+"/"+config["rawPlink"],
                        ".bed",".bim",".fam")
    log: "logs/make_plink"
            
    run:
        plink = config["plinklocal"]
        # Clumsy, but generic
        inTrunk =  mqc.plinkBase(input.bedset[0])
        outTrunk =  mqc.plinkBase(output.bedset[0])
        mqc.create_fam_map(inTrunk+".fam",
                           input.biobank2sentrix_map,
                           output.recode_ids,
                           config["rawPlink"])
        subprocess.run([plink,
                        "--bfile",inTrunk,
                        "--update-ids", output.recode_ids,
                        "--out", outTrunk,
                        "--make-bed"], check=True)
        # .nosex file still contains unmapped ids so it must die
        Path(outTrunk+".nosex").unlink(missing_ok=True)

