---
title: "generate-recode-files-rot2"
author: "Øyvind Helgeland"
date: "March 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(foreign)
library(tidyr)
```

```{r}
# Load file with SampleID and SentrixID for Rotterdam2
samples <- read.table('/home/oyvind/hunt-cloud/mnt/archive/ROTTERDAM2/delivery-fhi/data/raw-data/GS/GSA2017_246_025_STS-Rfriendly.tab', 
           header = T, stringsAsFactors = F, sep='\t')

# Load retID to pregID connection from FHI
con <- read.spss(file = '/home/oyvind/hunt-cloud/mnt/archive/ROTTERDAM2/connections/Kvalitetskontroll_MoBa_PDB315_926_930.sav', to.data.frame = T)

# Load gender from MFR
mfr <- read.spss('/home/oyvind/hunt-cloud/mnt/archive/moba/pheno/v10/raw/spss/2018_02_01_PDB315_MFR_520_v10.sav', to.data.frame = T)

# Load fam file
fam <- read.table('/home/oyvind/hunt-cloud/mnt/archive/ROTTERDAM2/delivery-fhi/data/raw-data/plink/GSA2017_246_025_ReRun.fam', 
                  header = F, 
                  stringsAsFactors = F)
names(fam) <- c('FID','IID','PID','MID','SEX','PHENO')
```

```{r}
# Gather and rename ROLES
con2 <- gather(con, 'retrievalDetail_ID_B_315_926_930', 'retrievalDetail_ID_M_315_926_930', 'retrievalDetail_ID_F_315_926_930', key='role', value='retID') %>%
  mutate(role = replace(role, role == 'retrievalDetail_ID_B_315_926_930', 'CHILD')) %>%
  mutate(role = replace(role, role == 'retrievalDetail_ID_M_315_926_930', 'MOTHER')) %>%
  mutate(role = replace(role, role == 'retrievalDetail_ID_F_315_926_930', 'FATHER'))

# Remove samples NA for retID (incomplete triads)
con3 <- con2 %>% drop_na(retID)
```

```{r}
# Extract gender from MFR
gender <- mfr %>% select(PREG_ID_315, KJONN)
```

```{r}
# Subset children in con3
con3.child <- subset(con3, role =="CHILD")

# Merge gender from MFR with children and recode 1=male, 2=female 
con3.child.gender <- merge(con3.child, gender, by='PREG_ID_315') %>% 
  dplyr::rename(sex = KJONN) %>% 
  mutate(sex = as.character(sex)) %>%
  mutate(sex = replace(sex, sex =='Boy',1)) %>%
  mutate(sex = replace(sex, sex =='Girl',2)) %>%
  mutate(sex = as.numeric(sex))

# Subset parents in con3 and recode sex
con3.parents.gender <- con3 %>% 
  filter(role == "MOTHER" |  role == "FATHER") %>% 
  mutate(sex = ifelse(role=="FATHER",1,2))

# Bind children and parents
con4 <- rbind(con3.child.gender, con3.parents.gender)

```

```{r}
# Some retIDs are duplicated
sum(duplicated(con4$retID))

# Show them
con4[duplicated(con3$retID),]

#

```
 

```{r}
# Merge SentrixID with connection table
m1 <- merge(samples, con4, by.x = 'Sample_ID', by.y = 'retID') %>% 
  select(PREG_ID_315, ArrayPicker, Sample_ID, sex, role) %>%
  mutate(pregid_retid = paste0(PREG_ID_315,'_',Sample_ID))

```

```{r}
# Some pregIDs have some members from another pregnancy (only mothers or fathers)
# To select the pregID with most members (to assign the to the correct pedigree)
# bind these parents to their "triad"

# Find how many samples are in each triad
#in_triad <- con4 %>% mutate(in_triad = rowSums(.[3:5]))

# Get the duplicated 
#dups <- con4[duplicated(con3$retID),]$retID

#dups.remove <- t %>% filter(retID %in% dups) %>% arrange(-intriad) %>% filter(duplicated(retID))

# Add a column summing the number of members per triad
con4$in_triad <- rowSums(con4[3:5])

# Generate a list with the duplicated samples to remove. This will make it possible to remove
# the retID and the associated pregID with the least samples only 
dups.remove <- con4 %>%
  filter(retID %in% dups) %>% 
  arrange(-in_triad) %>% 
  filter(duplicated(retID)) %>%
  mutate(pregid_retid = paste0(PREG_ID_315,'_',retID))

# Add a column in con4 to filter by
con4 <- con4 %>% mutate(pregid_retid = paste0(PREG_ID_315,'_',retID))

# Remove the duplicated retIDs
con5 <- subset(con4, !pregid_retid %in% dups.remove$pregid_retid)

# CHECK: All the SampleIDs/retIDs in samples file exists in con5
sum(samples$Sample_ID %in% con5$retID)

# CHECK: Two samples (children) in the connection file are not in the sample file
# might be due to failed genotyping
con5[!con5$retID %in% samples$Sample_ID,]

# Make a df with only the samples in the samples file to avoid confusion downstream
con6 <- con5[con5$retID %in% samples$Sample_ID,]
out <- m1 %>% filter(pregid_retid %in% con6$pregid_retid)

# Create a new FID to avoid using project specific PREG_ID
out$newfid <- as.numeric(factor(out$PREG_ID_315))
```

```{r}
# Merge fam with sample info
m3 <- merge(out, fam, by.x='Sample_ID', by.y='IID')
```

```{r}
# RECODE IDS
############

# Build recode ids file
recode.ids <- m3 %>% select(FID, Sample_ID, newfid, ArrayPicker)

write.table(recode.ids, 
            file = '/home/oyvind/hunt-cloud/mnt/archive/ROTTERDAM2/delivery-fhi/data/aux/recode-files/recode-files-original-fhi/recode-ids-rotterdam2.txt', 
            col.names = F, 
            row.names = F, 
            quote = F, 
            sep = ' ')
```

```{r}
# RECODE PARENTS
################

# Collapse data frame to get parents per child
recode.parents <- spread(m3, role, ArrayPicker) %>% 
  group_by(newfid) %>% 
  replace(., is.na(.), "") %>% 
  summarise_all(funs(trimws(paste(., collapse = '')))) %>% 
  select(newfid, CHILD, FATHER, MOTHER) %>% 
  data.frame()

# Replace empty strings with 0
recode.parents[recode.parents==""]<-0

# Remove all rows where the index sample (child) is 0
recode.parents.out <- subset(recode.parents, CHILD != 0)

# Write to file
write.table(recode.parents.out, 
            file = '/home/oyvind/hunt-cloud/mnt/archive/ROTTERDAM2/delivery-fhi/data/aux/recode-files/recode-files-original-fhi/recode-parents-rotterdam2.txt', 
            col.names = F, 
            row.names = F, 
            quote = F, 
            sep = ' ')

```

```{r}
# RECODE SEX
############

recode.sex <- m3 %>% select(newfid, ArrayPicker, sex)

# Write to file
write.table(recode.sex, 
            file = '/home/oyvind/hunt-cloud/mnt/archive/ROTTERDAM2/delivery-fhi/data/aux/recode-files/recode-files-original-fhi/recode-sex-rotterdam2.txt', 
            col.names = F, 
            row.names = F, 
            quote = F, 
            sep = ' ')

```

