# Used by various reporting to describe the set

dataSet: "Rotterdam2"
chip: "illumina GSA-MD 24 v1.0"
output_base: "/mnt/work/gutorm/qcTest/qcrot2/fullNewOutput"


# Lab QC report: /mnt/archive/ROTTERDAM2/delivery-fhi/data/raw-data/lab-report/GSA2017_246_QC_report.pdf
raw_bed_stem: "/mnt/archive/ROTTERDAM2/delivery-fhi/data/raw-data/plink/GSA2017_246_025_ReRun"

# old recode_rsid: "/mnt/archive/ROTTERDAM2/delivery-fhi/data/aux/recode-files/recode-rsid.txt"
# recode based on https://support.illumina.com/array/array_kits/infinium-global-screening-array/downloads.html (GSA v1.0)
recode_rsid: "/mnt/archive/chip-support-files/GSAMD24-v1.0/GSA-24v1-0_C1_b150_rsids.txt"

# MOBA info
recode_ids: "/mnt/archive/ROTTERDAM2/delivery-fhi/data/aux/recode-files/recode-files-original-fhi/recode-ids-rotterdam2.txt"
recode_parents: "/mnt/archive/ROTTERDAM2/delivery-fhi/data/aux/recode-files/recode-files-original-fhi/recode-parents-rotterdam2.txt"
recode_sex: "/mnt/archive/ROTTERDAM2/delivery-fhi/data/aux/recode-files/recode-files-original-fhi/recode-sex-rotterdam2.txt"

# GenomeStudio produced. Note that headers here are chip-dependent.
snptable: "/mnt/archive/ROTTERDAM2/delivery-fhi/data/raw-data/snptable/snp_table_rotterdam2.txt"

# Thresholds and names of the columns in snptable-file
cluster_sep_thr: 0.40
cluster_sep_col_name: "GSAMD-24v1-0_20011747_A4.bpm.Cluster Sep"
10%_GC_score_thr: 0.30
10%_GC_score_col_name: "10% GC"
aa_theta_dev_thr: 0.04
aa_theta_dev_col_name: "GSAMD-24v1-0_20011747_A4.bpm.AA T Dev"
#
# Minor allele frequency used in maf_removal plink --maf
maf_thr: 0.10
# Missing genotype threshold (samples) plink --mind
mind_thr: 0.05
# Missing genotype threshold (markers) plink --geno
geno_thr: 0.02
# Hardy-Weinberg equilibrium tests plink --hwe
hwe_thr: 0.0001
# prune_markers --make founders (command and params).
prune_cmd: --indep-pairwise 200 100 0.1
#
# these two files have been produced by Jonas by hand and have better pedigree info than we had
# We want to automate this - but for now (2019) we are just keeping it as it is
infer_recfam: "/mnt/archive/ROTTERDAM2/delivery-fhi/documentation/inferred-pedigree/permanent_reconstruct-fam.txt"
infer_badids: "/mnt/archive/ROTTERDAM2/delivery-fhi/documentation/inferred-pedigree/permanent_bad-sample-IIDs.txt"

# See https://cran.r-project.org/web/packages/plinkQC/vignettes/Genomes1000.pdf
# Reference is p37
1000_genomes_stem: "/mnt/work/gutorm/1000Genomes/all_phase3"
1000_genomes_pop: "/mnt/work/gutorm/1000Genomes/all_phase3.psam"
1kgp_maf_thr: 0.01
1kgp_prune_cmd: --indep-pairwise 100 50 0.1

# hapmap ... Old reference set b36 - We switch to G1000
# note that there is a full set bedset here ...
#hapmap_stem: "/mnt/archive/helgeland/refdata/hapmap/hapmap_b36/hapmapb36"
#hapmap_pop: "/mnt/archive/helgeland/refdata/hapmap/relationships_w_pops_121708.txt"






pca_thr: "6 0.015 NA 0.0355 NA"

hrc_sites: "/mnt/archive/helgeland/refdata/HRC/HRC.r1-1.GRCh37.wgs.mac5.sites.tab"




