# Config files containing hard coded variables
sys.path.append('../lib')  # in order to find our local packages
import mobaQcTools as mqc  # local moba package

# configfile: "configR3.yaml" # for running rotterdam3 tests
configfile: "config.yaml" 

#ensure bash as shell
shell.executable("/bin/bash")

# Runtime variables
include: "variables.py"
# A file with rule properites and ordering
with open("rules.yaml", 'r') as stream:
    rule_info = yaml.safe_load(stream)

# Report (top level)
report: "report/qc.rst"

# rule all
rule all:
    input:
        # For now, this is hardly used, but needed for -R. Edit a late result inn here
        #resultPath/"kgp_x_high_ld_autosome.yaml",
        #expand(str(resultPath) + "/{role}/ibd_prep.png", role=ROLES),
        #
        # Forcing documentation of fu_detector
        (resultPath/"pedigree_fu_detector_solver_pruned").with_suffix(".yaml"),
        expand(str(tmpMod2) + "/{role}/ibd_pruned.txt", role=ROLES),
        expand(str(resultPath) + "/{role}/geno_rates_mind3.yaml", role=ROLES),
        expand(str(resultPath) + "/{role}/hwe_autos_geno.yaml", role=ROLES),
        expand(str(resultPath) + "/{role}/sex_check.yaml", role=ROLES),
        expand(str(resultPath) + "/{role}/par_regions.yaml", role=ROLES),
        # For now: this is needed to force the plots into the report. Fix later
        resultPath/"plot_pca_both.png",
        expand(str(resultPath/"{role}/ibd_prep.png"), role=ROLES),
        expand(str(resultPath/"{role}/pihat_accum.png"), role=ROLES),
	# final output:
        # expand(config['output_base'] + 'mod5-shaping-preparation/tmp/hrc-update-complete-{chr}' + '{ext}', ext=['.bed','.bim','.fam'], chr=chrom),
	# expand(config['output_base'] + '{role}/pca/final_pca_covars.txt', role=ROLES),
	# config['output_base'] + 'sample_flag_list.txt'


# Include modules
include: "mod1-data-conversion.snake"
include: "mod2-core-cleaning.snake"
#include: "mod5-phasing-prep.snake"
